tags:
  - Tasks
summary: Delete task by id
operationId: deleteTask
description: 'Delete task by id. Please provide only valid mongodb id'
security:
  - bearerAuth: []
parameters:
  - in: path
    name: id
    required: true
    schema:
      type: string
      example: '65ca67e7ae7f10c88b598384'
      description: 'Please provide only valid MongoDB id'
responses:
  '200':
    description: 'Contact task successfully.'
    content:
      application/json:
        schema:
          type: object
          required:
            - data
          properties:
            status:
            data:
              type: object
              $ref: '../../../components/schemas/task.yaml'
  '401':
    $ref: '../../../components/responses/401.yaml'
  '404':
    description: 'Task not found.'
