tags:
  - Tasks
summary: Get task by id
operationId: getTask
description: 'Get task by id. Please provide only valid mongodb id'
security:
  - bearerAuth: []
parameters:
  - in: path
    name: id
    required: true
    schema:
      type: string
      example: '65ca67e7ae7f10c88b598384'
      description: 'Please provide only valid MongoDB id'
responses:
  '200':
    description: 'Get task by id'
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully found task with id 65ca67e7ae7f10c88b598384!
            data:
              type: object
              $ref: '../../../components/schemas/task.yaml'
  '401':
    $ref: '../../../components/responses/401.yaml'
