openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of tasks app
tags:
  - name: Tasks
    description: Operations about tasks.
servers:
  - url: http://localhost:3000
  - url: https://hw7-swagger-cd2c.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/post.yaml'
  /tasks:
    get:
      $ref: ../swagger/paths/tasks/get.yaml
    post:
      $ref: ../swagger/paths/tasks/post.yaml
  /tasks/{id}:
    get:
      $ref: ../swagger/paths/tasks/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/tasks/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/tasks/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
