tags:
  - Tasks
summary: Get list of task
operationId: getTasks
description: 'Get list of tasks with this endpoint'
security:
  - bearerAuth: []
parameters:
  - in: query
    name: page
    schema:
      type: integer
      example: 1
  - in: query
    name: perPage
    schema:
      type: integer
      example: 10
  - in: query
    name: status
    schema:
      type: string
      enum: ['todo', 'in-progress', 'review', 'done', 'blocked', 'canceled']
      example: todo
responses:
  '200':
    description: Successfully found tasks!
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully found tasks!
            data:
              type: object
              required:
                - data
                - page
                - perPage
                - totalItems
                - totalPages
              properties:
                tasks:
                  type: array
                  items:
                    $ref: ../../components/schemas/task.yaml
                page:
                  type: number
                  example: 1
                perPage:
                  type: number
                  example: 10
                totalItems:
                  type: number
                  example: 21
                totalPages:
                  type: number
                  example: 3
  '401':
    $ref: '../../components/responses/401.yaml'
