tags:
  - Tasks
summary: Create task
operationId: createTasks
description: 'Create a task with payload'
security:
  - bearerAuth: []
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        required:
          - title
          - description
          - status
        properties:
          title:
            description: "Task's title"
            type: string
            example: 'Docs'
          description:
            description: "Task's description"
            type: string
            example: 'Update API documentation'
          status:
            type: string
            enum:
              - todo
              - in-progress
              - review
              - done
              - canceled
              - blocked
            example: 'todo'
responses:
  '201':
    description: Creates a task
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/task.yaml
        example:
          id: '65e4decdd286b30065d54af9'
          title: 'Docs'
          description: 'Update API documentation'
          status: 'todo'
          createdAt: '2025-08-19T13:40:27.551Z'
          updatedAt: '2025-08-19T13:40:27.551Z'
  '401':
    $ref: '../../components/responses/401.yaml'
